// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxJgQo6KrrPW7owW7OlGpdUZ5pZs8aOoM',
    appId: '1:972184746650:web:9d814216ac192fcf933d23',
    messagingSenderId: '972184746650',
    projectId: 'yasmina-6f263',
    authDomain: 'yasmina-6f263.firebaseapp.com',
    storageBucket: 'yasmina-6f263.firebasestorage.app',
    measurementId: 'G-97TT2R4YSH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx6yRp8L2Cc-CrCuj9ANeTxGpFH795B54',
    appId: '1:972184746650:android:bfdf9594d9ef4617933d23',
    messagingSenderId: '972184746650',
    projectId: 'yasmina-6f263',
    storageBucket: 'yasmina-6f263.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQN76nj_CBdSPmT8FlG63EeQZ8gjuJ09Y',
    appId: '1:972184746650:ios:c49fa004c6f2684e933d23',
    messagingSenderId: '972184746650',
    projectId: 'yasmina-6f263',
    storageBucket: 'yasmina-6f263.firebasestorage.app',
    androidClientId: '972184746650-qmt1piskfjrjrsr9gib30k9j7o9p4hda.apps.googleusercontent.com',
    iosClientId: '972184746650-99b8mrv5i7e4bevs8h768ph1b0udts8n.apps.googleusercontent.com',
    iosBundleId: 'com.example.dtc6464',
  );
}
